### 배열 생성하기

In [1]:
!pip install numpy

In [1]:
import numpy as np

#### 시퀀스 데이터로부터 배열 생성

In [4]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
a1.dtype

dtype('int32')

In [7]:
a2.dtype

dtype('float64')

In [9]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
a[1,1]

5

In [12]:
np.array([[0.5, 2.0, 0.01, 8], [0.1, 2.5 , 0.023, 8]])

array([[0.5  , 2.   , 0.01 , 8.   ],
       [0.1  , 2.5  , 0.023, 8.   ]])

#### 범위를 지정해 배열 생성

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
b2 = np.arange(5)
b2.shape

(5,)

In [6]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

#### 특별한 형태의 배열 생성

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
str_a1 = np.array(["1.567", "0.123", "5.123","9", "8"])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [15]:
str_a1.dtype

dtype('<U5')

In [13]:
num_a1.dtype

dtype('float64')

In [17]:
str_a2 = np.array(["1", "3", "5","7", "9"])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [18]:
str_a2.dtype

dtype('<U1')

In [19]:
num_a2.dtype

dtype('int32')

In [20]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

#### 난수 배열의 생성

In [21]:
np.random.rand(2,3)

array([[0.16950853, 0.48741468, 0.60596577],
       [0.54961868, 0.61698152, 0.10242665]])

In [22]:
np.random.rand(2,3,4)

array([[[0.44156905, 0.9950113 , 0.53589458, 0.81854795],
        [0.84011008, 0.26634704, 0.72500866, 0.44372761],
        [0.55822326, 0.83390459, 0.25824688, 0.8254261 ]],

       [[0.79568638, 0.48750586, 0.05738473, 0.75317959],
        [0.58134286, 0.5314025 , 0.94315118, 0.00345031],
        [0.04620567, 0.1111548 , 0.69975025, 0.81903835]]])

In [23]:
np.random.randint(10, size=(3,4))

array([[4, 6, 3, 3],
       [2, 2, 8, 0],
       [9, 6, 1, 2]])

In [24]:
np.random.rand(1, 30)

array([[0.42536297, 0.11588518, 0.42736951, 0.51633106, 0.40948361,
        0.73895182, 0.67278442, 0.80495964, 0.79059738, 0.53225541,
        0.20031643, 0.23581123, 0.11757902, 0.6650503 , 0.92259707,
        0.89556711, 0.59545054, 0.23747432, 0.98804044, 0.17775743,
        0.68471911, 0.11022497, 0.50435628, 0.0198714 , 0.8837183 ,
        0.80357672, 0.25711381, 0.69342109, 0.93848546, 0.54493943]])

### 배열의 연산

#### 기본 연산

In [26]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [27]:
arr1 + arr2

array([11, 22, 33, 44])

In [28]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [29]:
arr2 * 2

array([2, 4, 6, 8])

In [30]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [31]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [32]:
arr1 / arr2

array([10., 10., 10., 10.])

In [33]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [34]:
arr1 > 20

array([False, False,  True,  True])

#### 통계를 위한 연산

In [37]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [38]:
arr3.sum()

10

In [39]:
arr3.mean()

2.0

In [40]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [41]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [42]:
[arr3.min(), arr3.max()]

[0, 4]

In [43]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [44]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [45]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

#### 행렬 연산

In [47]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [48]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [49]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [50]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [51]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [52]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [53]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

### 배열의 인덱싱과 슬라이싱

#### 배열의 인덱싱

In [54]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [55]:
a1[0]

0

In [56]:
a1[4]

40

In [57]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [58]:
a1[[1,3,4]]

array([10, 30, 40])

In [59]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [60]:
a2[0,2]

30

In [61]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [62]:
a2[1]

array([40, 50, 60])

In [63]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [64]:
a2[1] = np.array([47,57,67])
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [65]:
a2[[0,2],[0,1]]

array([10, 80])

In [66]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [67]:
a[(a%2) == 0]

array([2, 4, 6])

In [68]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [69]:
b1[:3]

array([ 0, 10, 20])

In [70]:
b1[2:]

array([20, 30, 40, 50])

In [71]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [72]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [77]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [78]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [79]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [80]:
b2[1]

array([40, 50, 60])

In [81]:
b2[1][0:2]

array([40, 50])

In [84]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])