### 배열 생성하기

In [1]:
!pip install numpy

In [2]:
import numpy as np

#### 시퀀스 데이터로부터 배열 생성

In [4]:
data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
a1.dtype

dtype('int32')

In [7]:
a2.dtype

dtype('float64')

In [9]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [14]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
a[1,1]

5

In [12]:
np.array([[0.5, 2.0, 0.01, 8], [0.1, 2.5 , 0.023, 8]])

array([[0.5  , 2.   , 0.01 , 8.   ],
       [0.1  , 2.5  , 0.023, 8.   ]])

#### 범위를 지정해 배열 생성

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])